/* eslint-disable prettier/prettier */
export const accountGroups = [
  { id: 1, name: 'Current Assets', rootId: 1 },
  { id: 2, name: 'Other Current Assets', rootId: 1 },
  { id: 3, name: 'Fixed Assets', rootId: 1 },
  { id: 4, name: 'Investments', rootId: 1 },
  { id: 5, name: 'Accounts Receivable', rootId: 1 },
  { id: 6, name: 'Stock Assets', rootId: 1 },
  { id: 7, name: 'Bank', rootId: 1 },
  { id: 8, name: 'Cash', rootId: 1 },
  { id: 9, name: 'Current Liabilities', rootId: 2 },
  { id: 10, name: 'Other Current Liabilities', rootId: 2 },
  { id: 11, name: 'Other Liabilities', rootId: 2 },
  { id: 12, name: 'Accounts Payable', rootId: 2 },
  { id: 13, name: 'Duties and Taxes', rootId: 2 },
  { id: 14, name: 'Stock Liabilities', rootId: 2 },
  { id: 15, name: 'Equity', rootId: 3 },
  { id: 16, name: 'Direct Income', rootId: 4 },
  { id: 17, name: 'Indirect Income', rootId: 4 },
  { id: 18, name: 'Expense', rootId: 5 },
  { id: 19, name: 'Other Expense', rootId: 5 },
  { id: 20, name: 'Cost of Goods Sold', rootId: 5 },
];
