/* eslint-disable prettier/prettier */
export const accountGroups = [
  { name: 'Current Assets', type: 'Assets' },
  { name: 'Fixed Assets', type: 'Assets' },
  { name: 'Investments', type: 'Assets' },
  { name: 'Accounts Receivable', type: 'Assets' },
  { name: 'Stock Assets', type: 'Assets' },
  { name: 'Bank', type: 'Assets' },
  { name: 'Cash', type: 'Assets' },
  { name: 'Equity', type: 'Equity' },
  { name: 'Direct Expenses', type: 'Expenses' },
  { name: 'Indirect Expenses', type: 'Expenses' },
  { name: 'Stock Expenses', type: 'Expenses' },
  { name: 'Direct Income', type: 'Revenues' },
  { name: 'Indirect Income', type: 'Revenues' },
  { name: 'Current Liabilities', type: 'Liabilities' },
  { name: 'Accounts Payable', type: 'Liabilities' },
  { name: 'Duties and Taxes', type: 'Liabilities' },
  { name: 'Stock Liabilities', type: 'Liabilities' },
];
