/* eslint-disable prettier/prettier */
export const accountGroups = [
  { id: 1, name: 'current assets', rootId: 1 },
  { id: 2, name: 'other current assets', rootId: 1 },
  { id: 3, name: 'fixed assets', rootId: 1 },
  { id: 4, name: 'investments', rootId: 1 },
  { id: 5, name: 'accounts receivable', rootId: 1 },
  { id: 6, name: 'stock assets', rootId: 1 },
  { id: 7, name: 'bank', rootId: 1 },
  { id: 8, name: 'cash', rootId: 1 },
  { id: 9, name: 'current liabilities', rootId: 2 },
  { id: 10, name: 'other current liabilities', rootId: 2 },
  { id: 11, name: 'other liabilities', rootId: 2 },
  { id: 12, name: 'accounts payable', rootId: 2 },
  { id: 13, name: 'duties and taxes', rootId: 2 },
  { id: 14, name: 'stock liabilities', rootId: 2 },
  { id: 15, name: 'equity', rootId: 3 },
  { id: 16, name: 'direct income', rootId: 4 },
  { id: 17, name: 'indirect income', rootId: 4 },
  { id: 18, name: 'expense', rootId: 5 },
  { id: 19, name: 'other expense', rootId: 5 },
  { id: 20, name: 'cost of goods sold', rootId: 5 },
];
